### ISSUE TITLE
How do I prevent scrolling after resizing the container?

### ISSUE THREAD

**Issue by beshur** [mattermost/dynamic-virtualized-list#23]
Hello.

I am bulding a chat app, and we have another resizeable container above the chat messages list.

Messages list is `DynamicSizeList` wrapped in `AutoSizer` (react-virtualized-auto-sizer).

So when I resize the top container, the messages list gets scrolled up about 100%. 

I can't see what I can do about it.

Can't make a reproducible example at the moment.

**Comment by beshur** [comment]
After reading the source code, I noticed that it has to deal with `scrollUpdateWasRequested`, but I can't see a way to influence it.

Could you please help?

**Comment by naftalimurgor** [comment]
Could you please post screenshots or code samples if available. I'd be a great way to see how the issue is reproducible.

**Comment by beshur** [comment]
Hello.

Sure.

Please see the [screencast video](https://drive.google.com/file/d/1dnQVtc_whv7QZSVJ_9YkOq7Zz3y6mLQS/view?usp=sharing).

Source https://github.com/beshur/tmp-react-scrollable
Demo https://eloquent-minsky-40a538.netlify.app/

**Comment by beshur** [comment]
Sorry, I think it does not relate to `AutoSizer` at all.

**Comment by beshur** [comment]
Sorry, this is still actual. 
I think this might be an issue with DynamicSizeList.

**Comment by beshur** [comment]
From my debugging, actually `AutoSizer` issue.

Sorry.

For reference https://github.com/bvaughn/react-virtualized/issues/1668

**Comment by naftalimurgor** [comment]
Hey @beshur, my appologies I got held up somewhere, but if you figured out the issue it's okay
